service: serverless-nodejs-app

provider:
  name: aws
  runtime: nodejs14.x
  stage: production # make sure to change this to production
  region: us-east-1
  environment:
    DYNAMODB_TABLE: 'Words_Main_DB'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'

    # reference the NODE_ENV from the secrets.json file
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
